import glob
import hashlib
import os
import re

import bpy

from ..utils.timer_utils import TimerUtils
from ..utils.command_utils import CommandUtils
from ..utils.translate_utils import rpt_

from ..common.global_config import GlobalConfig
from ..common.global_config import LogicName

from ..games.efmi import ExportEFMI
from ..games.gimi import ExportGIMI
from ..games.himi import ExportHIMI
from ..games.identityv import ExportIdentityV
from ..games.snowbreak import ExportSnowBreak
from ..games.cami import ExportCAMI
from ..games.srmi import ExportSRMI
from ..games.unity import ExportUnity
from ..games.wwmi import ExportWWMI
from ..games.ntemi import ExportNTEMI
from ..games.yysls import ExportYYSLS
from ..games.zzmi import ExportZZMI
from ..games.zzmidx12 import ExportZZMIDX12

from ..model.blueprint_model import BluePrintModel
from ..blueprint.blueprint_export_helper import BlueprintExportHelper
from ..blueprint.blueprint_node_obj import ObjectPersistentIdManager
from ..blueprint.blueprint_node_face_mod import (
    FaceModExportError,
    export_face_mod_from_node,
)


def _export_blueprint_model(blueprint_model):
    """Dispatch one parsed output layer to the selected game exporter."""
    if GlobalConfig.logic_name == LogicName.EFMI:
        ExportEFMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.GIMI:
        ExportGIMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.HIMI:
        ExportHIMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.IdentityV:
        ExportIdentityV(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.SRMI:
        ExportSRMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.ZZMIDX12:
        ExportZZMIDX12(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.ZZMI:
        ExportZZMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.WWMI:
        ExportWWMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.NTEMI:
        ExportNTEMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.SnowBreak:
        ExportSnowBreak(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.CAMI:
        ExportCAMI(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name == LogicName.YYSLS:
        ExportYYSLS(blueprint_model=blueprint_model).export()
    elif GlobalConfig.logic_name in {
        LogicName.Naraka, LogicName.NarakaM, LogicName.GF2, LogicName.AILIMIT,
    }:
        ExportUnity(blueprint_model=blueprint_model).export()
    else:
        raise ValueError("当前游戏预设暂不支持生成Mod")


def _safe_output_config_name(node, index, used_names):
    raw_name = str(getattr(node, "ini_filename", "") or "").strip()
    if not raw_name:
        raw_name = f"{GlobalConfig.get_workspace_name()}_output_{index + 1}.cfg"
    raw_name = os.path.basename(raw_name.replace("\\", "/"))
    raw_name = re.sub(r"[^A-Za-z0-9_.-]", "_", raw_name)
    if not raw_name or raw_name in {".", ".."}:
        raw_name = f"{GlobalConfig.get_workspace_name()}_output_{index + 1}.cfg"
    stem, _ = os.path.splitext(raw_name)
    raw_name = stem + ".cfg"
    stem, extension = os.path.splitext(raw_name)
    candidate = raw_name
    suffix = 2
    while candidate.casefold() in used_names:
        candidate = f"{stem}_{suffix}{extension}"
        suffix += 1
    used_names.add(candidate.casefold())
    return candidate


def _include_path(ini_path, included_path):
    """Return the nested-INI path understood by 3DMigoto's namespace parser."""
    return os.path.relpath(included_path, os.path.dirname(ini_path)).replace("/", "\\")


def _prepend_ini_includes(ini_path, included_paths):
    if not included_paths:
        return
    with open(ini_path, "r", encoding="utf-8") as ini_file:
        body = ini_file.read()
    body = re.sub(r"\n;sha256=[0-9a-fA-F]+\s*\Z", "\n", body)
    # Replace a previous generated include block so repeated exports remain
    # stable instead of nesting the same references indefinitely.
    body = re.sub(
        r"\A; Generated by TheHerta4 SSMT chained includes\.\n\n\[Include\]\n"
        r"(?:include = [^\r\n]+\r?\n)+\r?\n?",
        "",
        body,
    )
    include_header = (
        "; Generated by TheHerta4 SSMT chained includes.\n\n"
        "[Include]\n"
        + "".join(f"include = {_include_path(ini_path, path)}\n" for path in included_paths)
        + "\n"
    )
    body = include_header + body.lstrip("\r\n")
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    with open(ini_path, "w", encoding="utf-8", newline="\n") as ini_file:
        ini_file.write(body.rstrip("\n") + f"\n\n;sha256={digest}\n\n")


_OUTPUT_NODE_IDS = {"SSMTNode_Result_Output", "SSMTNode_Face_Mod_Export"}


def _direct_upstream_outputs(node):
    return [
        source for source in BlueprintExportHelper.get_connected_nodes(node)
        if getattr(source, "bl_idname", "") in _OUTPUT_NODE_IDS
    ]


def _export_regular_output(tree, context, output_node, config_name):
    output_folder = GlobalConfig.path_generate_mod_folder()
    stem = os.path.splitext(config_name)[0]
    GlobalConfig.generated_mod_name_override = stem
    BlueprintExportHelper.runtime_output_node = output_node
    blueprint_model = None
    try:
        blueprint_model = BluePrintModel(tree=tree, context=context, output_node=output_node)
        _export_blueprint_model(blueprint_model)
    finally:
        if blueprint_model is not None:
            _cleanup_unico_temp_objects(blueprint_model)
        BlueprintExportHelper.runtime_output_node = None
        GlobalConfig.generated_mod_name_override = ""

    if GlobalConfig.logic_name == LogicName.WWMI:
        generated = sorted(glob.glob(os.path.join(output_folder, stem + "_*.ini")))
    else:
        generated = [os.path.join(output_folder, stem + ".ini")]
    generated = [path for path in generated if os.path.isfile(path)]
    if not generated:
        raise ValueError(f"输出节点 '{output_node.name}' 未生成 INI 文件")
    return generated


def _generate_output_node(tree, context, output_node, state, *, is_root=False):
    """Generate one Output node after its direct Output parents.

    The returned INIs are deliberately only the current node's files.  This
    keeps Include links topological: A -> B -> C becomes C includes B and B
    includes A, never C including A directly.
    """
    if output_node in state["active"]:
        raise ValueError("生成 Mod 输出节点之间存在循环连接")
    if output_node in state["generated"]:
        return state["generated"][output_node]

    state["active"].add(output_node)
    try:
        upstream_paths = []
        for parent in _direct_upstream_outputs(output_node):
            upstream_paths.extend(_generate_output_node(tree, context, parent, state))

        if getattr(output_node, "bl_idname", "") == "SSMTNode_Face_Mod_Export":
            face_ini, _ = export_face_mod_from_node(output_node)
            generated_paths = [face_ini]
        else:
            config_name = (
                f"{GlobalConfig.get_workspace_name()}.ini"
                if is_root else _safe_output_config_name(
                    output_node, state["output_index"], state["used_names"]
                )
            )
            if not is_root:
                state["output_index"] += 1
            generated_paths = _export_regular_output(tree, context, output_node, config_name)

        # Included files must not also be picked up by d3dx.ini's
        # include_recursive = Mods scan.  A .cfg suffix is recognised by our
        # explicit [Include] but skipped by that recursive .ini discovery.
        if not is_root:
            config_paths = []
            for generated_path in generated_paths:
                config_path = os.path.splitext(generated_path)[0] + ".cfg"
                if os.path.normcase(config_path) != os.path.normcase(generated_path):
                    os.replace(generated_path, config_path)
                config_paths.append(config_path)
            generated_paths = config_paths

        for generated_path in generated_paths:
            _prepend_ini_includes(generated_path, upstream_paths)
        state["generated"][output_node] = generated_paths
        return generated_paths
    finally:
        state["active"].remove(output_node)


def generate_mod_from_output_node(tree, context, output_node, report_callback):
    if getattr(output_node, "bl_idname", "") not in _OUTPUT_NODE_IDS:
        report_callback({'ERROR'}, "请选择有效的 Output 节点")
        return {'CANCELLED'}

    TimerUtils.Start("GenerateMod Mod")
    GlobalConfig.initialize_key_count()
    BlueprintExportHelper.runtime_output_node = None
    BlueprintExportHelper.set_runtime_blueprint_tree(tree)
    refresh_summary = ObjectPersistentIdManager.refresh_all_nodes(tree=tree, source="export")
    if refresh_summary["missing_count"] > 0:
        report_callback({'WARNING'}, f"导出前有 {refresh_summary['missing_count']} 个物体节点未找到对应物体")

    state = {
        "active": set(), "generated": {}, "used_names": set(), "output_index": 0,
    }
    try:
        _generate_output_node(tree, context, output_node, state, is_root=True)
    except (FaceModExportError, OSError, ValueError) as error:
        BlueprintExportHelper.runtime_output_node = None
        GlobalConfig.generated_mod_name_override = ""
        TimerUtils.End("GenerateMod Mod")
        report_callback({'ERROR'}, str(error))
        return {'CANCELLED'}

    TimerUtils.End("GenerateMod Mod")
    report_callback({'INFO'}, rpt_("生成Mod成功！"))
    CommandUtils.OpenGeneratedModFolder()
    return {'FINISHED'}


def generate_mod_from_tree(tree, context, report_callback):
    if not tree:
        report_callback({'ERROR'}, "未找到有效的蓝图")
        return {'CANCELLED'}
    output_nodes = [
        node for node in tree.nodes
        if getattr(node, "bl_idname", "") in _OUTPUT_NODE_IDS
    ]
    if not output_nodes:
        report_callback({'ERROR'}, "当前蓝图缺少 Generate Mod 输出节点")
        return {'CANCELLED'}

    # The toolbar shortcut has no node identity.  Prefer the sole terminal
    # Output; with several independent targets users must click the intended
    # node so a root INI is never accidentally overwritten.
    terminal_nodes = []
    for node in output_nodes:
        output_socket = node.outputs[0] if getattr(node, "outputs", None) else None
        if not output_socket or not any(
            getattr(link.to_node, "bl_idname", "") in _OUTPUT_NODE_IDS
            for link in output_socket.links
        ):
            terminal_nodes.append(node)
    if len(terminal_nodes) != 1:
        report_callback({'ERROR'}, "存在多个独立 Output；请在要生成的 Output 节点上点击“生成 Mod”")
        return {'CANCELLED'}
    return generate_mod_from_output_node(tree, context, terminal_nodes[0], report_callback)


def _cleanup_unico_temp_objects(blueprint_model: BluePrintModel):
    """清理 UniComponent 拆分产生的临时物体"""
    temp_objects = getattr(blueprint_model, '_unico_temp_objects', None)
    if not temp_objects:
        return
    for temp_obj in temp_objects:
        try:
            if temp_obj and temp_obj.name in bpy.data.objects:
                bpy.data.objects.remove(temp_obj, do_unlink=True)
        except Exception as e:
            print(f"[UniComponent] 清理临时物体时出错: {e}")
    print(f"[UniComponent] 已清理 {len(temp_objects)} 个临时拆分物体")


class SSMTGenerateModBlueprint(bpy.types.Operator):
    bl_idname = "ssmt.generate_mod_blueprint"
    bl_label = "生成Mod"
    bl_description = "根据当前工作空间对应的蓝图架构生成对应的Mod文件"
    bl_options = {'REGISTER','UNDO'}

    node_name: bpy.props.StringProperty()  # type: ignore
    tree_name: bpy.props.StringProperty()  # type: ignore

    def execute(self, context):
        tree = bpy.data.node_groups.get(self.tree_name) if self.tree_name else None
        tree = tree or BlueprintExportHelper.get_current_blueprint_tree(context=context)
        if not tree:
            self.report({'ERROR'}, "未找到当前蓝图，请在蓝图编辑器中点击“生成Mod”")
            return {'CANCELLED'}
        if self.node_name:
            output_node = tree.nodes.get(self.node_name)
            if output_node is None:
                self.report({'ERROR'}, "未找到此 Output 节点")
                return {'CANCELLED'}
            return generate_mod_from_output_node(tree, context, output_node, self.report)
        return generate_mod_from_tree(tree=tree, context=context, report_callback=self.report)


class SSMTGenerateSelectedBlueprintMod(bpy.types.Operator):
    bl_idname = "ssmt.generate_selected_blueprint_mod"
    bl_label = "生成Mod"
    bl_description = "根据当前选中的蓝图快捷生成对应的Mod文件"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        global_properties = getattr(getattr(context, "scene", None), "global_properties", None)
        selected_name = getattr(global_properties, "selected_blueprint_name", "") if global_properties else ""

        tree = BlueprintExportHelper.get_selected_blueprint_tree(
            selected_name=selected_name,
            context=context,
        )
        if not tree:
            self.report({'ERROR'}, "请选择有效的蓝图")
            return {'CANCELLED'}

        if global_properties and global_properties.selected_blueprint_name != tree.name:
            global_properties.selected_blueprint_name = tree.name

        return generate_mod_from_tree(tree=tree, context=context, report_callback=self.report)
    
def register():
    bpy.utils.register_class(SSMTGenerateModBlueprint)
    bpy.utils.register_class(SSMTGenerateSelectedBlueprintMod)


def unregister():
    bpy.utils.unregister_class(SSMTGenerateSelectedBlueprintMod)
    bpy.utils.unregister_class(SSMTGenerateModBlueprint)

